// <auto-generated />
using System;
using Api.Features.ConsumptionDays;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ConsumptionDaysDbContext))]
    partial class ConsumptionDaysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Api.Features.ConsumptionDays.ConsumptionDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayComplete")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConsumptionDays");
                });
#pragma warning restore 612, 618
        }
    }
}
